### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by magnusstubman** [moxie0/sslstrip#16]
@moxie0 what's going on? Is this project dead?

**Comment by ngalongc** [comment]
Pretty much the same as dead after HSTS came in place. Almost all major website are using HSTS to prevent https->http directly.
But the project has rebirth in sslstrip2 in order to defeat HSTS. And the project clone is here.
https://github.com/byt3bl33d3r/sslstrip2

**Comment by sol-vin** [comment]
Ty for the info @ngalongc! Loved this tool but forced HTTPS made the attack impossible. Glad to see someone is trying to make it work again,

**Comment by matrixfox** [comment]
This project is deeeeaaaaaaaaad...
