### ISSUE TITLE
302 requests not working

### ISSUE THREAD

**Issue by sol-vin** [moxie0/sslstrip#8]
I was pulling my hair trying to figure out why sslstrip wasn't striping even though I was spoofing. After trying for a while I started getting these when loading new pages.

The first one happens on first load, the second one if you hit refresh really quickly after the first load. If you wait awhile the request goes through normally, but ssl still isn't stripped. :(
![a](https://f.cloud.github.com/assets/1298501/284528/d47b22fc-91ed-11e2-8e3a-38d0395314d1.png)
![b](https://f.cloud.github.com/assets/1298501/284533/0abb38e8-91ee-11e2-898b-e676bd0c484c.png)

**Comment by crblanaru** [comment]
Hey,

I've got a fix for that.

Cristian

**Comment by sol-vin** [comment]
Oh cool! So is this problem resolved?

**Comment by crblanaru** [comment]
Have a look under pull request ("Fix on location:ht issue in firefox and other related issues"). It should be sorted now. It might take a while until Moxie accepts the change though, so you might want to do the change manually.
